# Project information
site_name: 'Daspanel'
site_description: 'Daspanel documentation.'
site_author: 'Daspanel'
site_url: 'https://docs.daspanel.com'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/daspanel/daspanel'

# Copyright
copyright: 'Copyright (c) 2016-2018 Daspanel'

# Documentation and theme
docs_dir: 'docs'
site_dir: 'site_mkdocs'

# theme: 'material'
theme:
  name: material
  feature:
    tabs: true

#theme_dir: docs/custom_theme
#extra_css: [ custom_theme/extra.css ]

# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Options
extra:
  version: '0.1.0'
  logo: 'img/logo.png'
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
#  i18n:
#    prev: 'Previous'
#    next: 'Next'
  author:
    github: 'daspanel'
#    twitter: 'my-twitter-handle'
  social:
    - type: globe
      link: http://daspanel.com
    - type: 'github'
      link: 'https://github.com/daspanel'

# From https://github.com/juttle/juttle/blob/master/mkdocs.yml http://juttle.github.io/juttle/
# http://squidfunk.github.io/mkdocs-material/getting-started/#full-example

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# use_directory_urls: true

# Pages with ___Title are hidden from left sidebar menu.
pages:

# Pages with ___Title are hidden from left sidebar menu.

#- Introduction:
#   - 'About': 'index.md'
#   - '____ Docs README': 'README.md'
#   - '____ Doc Template': 'doc_templates/template.md'
#   - '____ Juttle Doc Template': 'doc_templates/juttle_TEMPLATE.md'
#   - '____ Sample Datasets': 'examples/datasets/README.md'

- Overview: 'index.md'
- How It Works: 'howitworks.md'
- Issues: 'issues.md'
- Contributing: 'contributing.md'
- Authors: 'authors.md'
- Installation guide:
    - 'Linux': 'help/install/linux.md'
    - 'Windows': 'help/install/windows.md'
    - 'Mac': 'help/install/mac.md'
- User Guide:
#    - Overview: 'help/wip.md'
#    - Understanding Daspanel:
#        - Concepts: 'help/wip.md'
#        - Architecture: 'help/wip.md'
#        - Components: 'help/wip.md'
    - Sites:
#        - Overview: 'help/wip.md'
        - Add: 'help/sites/add.md'
        - Edit: 'help/sites/edit.md'
        - Delete Site: 'help/sites/delete.md'
        - Console: help/sites/console.md
        - File Manager: help/sites/filemanager.md
        - Toolbox:
            - Overview: 'help/sites/toolbox/overview.md'
        - Versions:
            - Overview: 'help/sites/versions/overview.md'
            - Clone Version: 'help/sites/versions/clone.md'
            - Add Version: 'help/sites/versions/add.md'
            - Edit Version: 'help/sites/versions/edit.md'
            - Delete Version: 'help/sites/versions/delete.md'
            - Preview Version: 'help/sites/versions/preview.md'
            - Select Site Default Version: 'help/sites/versions/default.md'
            - Console: help/sites/versions/console.md
            - File Manager: help/sites/versions/filemanager.md
        - Domain Mapping:
            - Overview: 'help/sites/domain_mapping/overview.md'
            - Add: 'help/sites/domain_mapping/add.md'
            - Edit: 'help/sites/domain_mapping/edit.md'
            - Delete: 'help/sites/domain_mapping/delete.md'
            - Preview: 'help/sites/domain_mapping/preview.md'
            - Console: help/sites/domain_mapping/console.md
            - File Manager: help/sites/domain_mapping/filemanager.md
#        - Control: 'help/wip.md'
#        - Redirects: 'help/wip.md'
#        - Content Upload: 'help/wip.md'
    - Services:
        - File Manager: 'help/services/filemanager.md'
        - Database Manager: 'help/services/adminer.md'
        - S3 Storage: 'help/services/s3storage.md'
        - Mail Catcher: 'help/services/mailcatcher.md'
    - System:
        - Services Users: 'help/system/services_users.md'

- How To:
    - Sites:
        - 'Wordpress': 'howto/wp/index.md'
        - 'Static HTML/JS': 'howto/htmljs/index.md'
        - 'Grav': 'howto/grav/index.md'
        - 'Static Using VUE-CLI': 'howto/htmljs/vue-cli.md'
        - 'Deploy Static Site to Firebase': 'howto/htmljs/deploy2firebase.md'
        - Import:
            - 'Cpanel - Import Wordpress Site': 'howto/cpanel/import_wordpress.md'
    - Deploy:
        - Digital Ocean:
            - Static and PHP sites: 'howto/deploy/digitalocean.md'

#- User guide:
#    - 'Usingh docker-compose': 'help/compose.md'
#    - 'Advanced': 'help/advanced.md'
#    - 'Development': 'help/development.md'
#    - 'How To': 'howto/index.md'
#- About:
#    - 'Authors': 'authors.md'
#    - 'Changelog': 'changelog.md'

